title: Lightning Network Notes for Beginners
description: Collection of my learnings about lightning so that other people can find this information faster.
twitter:
  username: bensig
  card: summary
image: https://upload.wikimedia.org/wikipedia/commons/5/5a/Lightning_Network.svg
title: Lightning Network Notes for Beginners
description: These are helpful notes I have compiled about the Bitcoin Lightning Network.
